# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x18\x63om.deepwisdom.grpc.user\"\x1a\n\tIdRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"\x1c\n\nIdResponse\x12\x0e\n\x06userId\x18\x01 \x01(\x05\" \n\x0eUserIdsRequest\x12\x0e\n\x06userId\x18\x01 \x03(\x05\"%\n\x13UserMobilesResponse\x12\x0e\n\x06mobile\x18\x01 \x03(\t\"!\n\x10UserTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"U\n\x10UserInfoResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0e\n\x06mobile\x18\x04 \x01(\t2\xba\x02\n\x0bUserService\x12V\n\tgetUserId\x12#.com.deepwisdom.grpc.user.IdRequest\x1a$.com.deepwisdom.grpc.user.IdResponse\x12i\n\x0egetUserMobiles\x12(.com.deepwisdom.grpc.user.UserIdsRequest\x1a-.com.deepwisdom.grpc.user.UserMobilesResponse\x12h\n\x0egetUserByToken\x12*.com.deepwisdom.grpc.user.UserTokenRequest\x1a*.com.deepwisdom.grpc.user.UserInfoResponseB\x02P\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _IDREQUEST._serialized_start=40
  _IDREQUEST._serialized_end=66
  _IDRESPONSE._serialized_start=68
  _IDRESPONSE._serialized_end=96
  _USERIDSREQUEST._serialized_start=98
  _USERIDSREQUEST._serialized_end=130
  _USERMOBILESRESPONSE._serialized_start=132
  _USERMOBILESRESPONSE._serialized_end=169
  _USERTOKENREQUEST._serialized_start=171
  _USERTOKENREQUEST._serialized_end=204
  _USERINFORESPONSE._serialized_start=206
  _USERINFORESPONSE._serialized_end=291
  _USERSERVICE._serialized_start=294
  _USERSERVICE._serialized_end=608
# @@protoc_insertion_point(module_scope)
